const dataCountryDummy = [{
    "name": "Brazil",
    "value": "Israel"
  }, {
    "name": "Afghanistan",
    "value": "China"
  }, {
    "name": "Slovenia",
    "value": "Vietnam"
  }, {
    "name": "Indonesia",
    "value": "Philippines"
  }, {
    "name": "Brazil",
    "value": "Indonesia"
  }, {
    "name": "Colombia",
    "value": "Tanzania"
  }, {
    "name": "Portugal",
    "value": "Mexico"
  }, {
    "name": "China",
    "value": "Indonesia"
  }, {
    "name": "China",
    "value": "Croatia"
  }, {
    "name": "China",
    "value": "Japan"
  }, {
    "name": "Indonesia",
    "value": "Philippines"
  }, {
    "name": "Lithuania",
    "value": "China"
  }, {
    "name": "Russia",
    "value": "France"
  }, {
    "name": "Indonesia",
    "value": "China"
  }, {
    "name": "Indonesia",
    "value": "Indonesia"
  }, {
    "name": "Ukraine",
    "value": "Colombia"
  }, {
    "name": "Argentina",
    "value": "Malaysia"
  }, {
    "name": "Colombia",
    "value": "Russia"
  }, {
    "name": "United States",
    "value": "Philippines"
  }, {
    "name": "Czech Republic",
    "value": "Paraguay"
  }, {
    "name": "China",
    "value": "Nicaragua"
  }, {
    "name": "Sri Lanka",
    "value": "Pakistan"
  }, {
    "name": "Madagascar",
    "value": "Philippines"
  }, {
    "name": "France",
    "value": "Russia"
  }, {
    "name": "Philippines",
    "value": "Serbia"
  }, {
    "name": "Portugal",
    "value": "Bulgaria"
  }, {
    "name": "Mexico",
    "value": "Bolivia"
  }, {
    "name": "Indonesia",
    "value": "Brazil"
  }, {
    "name": "Japan",
    "value": "Philippines"
  }, {
    "name": "France",
    "value": "Djibouti"
  }, {
    "name": "Russia",
    "value": "Jordan"
  }, {
    "name": "Albania",
    "value": "China"
  }, {
    "name": "China",
    "value": "Indonesia"
  }, {
    "name": "Argentina",
    "value": "Indonesia"
  }, {
    "name": "Netherlands",
    "value": "China"
  }, {
    "name": "Poland",
    "value": "Ecuador"
  }, {
    "name": "Portugal",
    "value": "Brazil"
  }, {
    "name": "Indonesia",
    "value": "Indonesia"
  }, {
    "name": "South Korea",
    "value": "Palestinian Territory"
  }, {
    "name": "Russia",
    "value": "Belarus"
  }, {
    "name": "Belarus",
    "value": "Czech Republic"
  }, {
    "name": "Brazil",
    "value": "Serbia"
  }, {
    "name": "Portugal",
    "value": "Indonesia"
  }, {
    "name": "Cuba",
    "value": "Philippines"
  }, {
    "name": "Colombia",
    "value": "Russia"
  }, {
    "name": "China",
    "value": "Indonesia"
  }, {
    "name": "Indonesia",
    "value": "Canada"
  }, {
    "name": "Ukraine",
    "value": "China"
  }, {
    "name": "Malaysia",
    "value": "Albania"
  }, {
    "name": "Iran",
    "value": "Poland"
  }, {
    "name": "Russia",
    "value": "Ethiopia"
  }, {
    "name": "Russia",
    "value": "Benin"
  }, {
    "name": "Indonesia",
    "value": "Indonesia"
  }, {
    "name": "Indonesia",
    "value": "Dominica"
  }, {
    "name": "China",
    "value": "Malaysia"
  }, {
    "name": "United States",
    "value": "Kosovo"
  }, {
    "name": "Portugal",
    "value": "Indonesia"
  }, {
    "name": "Brazil",
    "value": "Indonesia"
  }, {
    "name": "Russia",
    "value": "Brazil"
  }, {
    "name": "Cayman Islands",
    "value": "Thailand"
  }, {
    "name": "Russia",
    "value": "Paraguay"
  }, {
    "name": "Belarus",
    "value": "China"
  }, {
    "name": "China",
    "value": "China"
  }, {
    "name": "Greece",
    "value": "Ethiopia"
  }, {
    "name": "Indonesia",
    "value": "Russia"
  }, {
    "name": "Russia",
    "value": "Indonesia"
  }, {
    "name": "China",
    "value": "Portugal"
  }, {
    "name": "China",
    "value": "Dominican Republic"
  }, {
    "name": "Sweden",
    "value": "Indonesia"
  }, {
    "name": "Poland",
    "value": "China"
  }, {
    "name": "France",
    "value": "China"
  }, {
    "name": "Norway",
    "value": "Brazil"
  }, {
    "name": "United States",
    "value": "Iran"
  }, {
    "name": "China",
    "value": "Czech Republic"
  }, {
    "name": "Vietnam",
    "value": "Dominican Republic"
  }, {
    "name": "China",
    "value": "Afghanistan"
  }, {
    "name": "Azerbaijan",
    "value": "Thailand"
  }, {
    "name": "Azerbaijan",
    "value": "China"
  }, {
    "name": "China",
    "value": "Poland"
  }, {
    "name": "Sweden",
    "value": "Ecuador"
  }, {
    "name": "Moldova",
    "value": "Canada"
  }, {
    "name": "Ukraine",
    "value": "France"
  }, {
    "name": "Kyrgyzstan",
    "value": "Philippines"
  }, {
    "name": "Bosnia and Herzegovina",
    "value": "Colombia"
  }, {
    "name": "Philippines",
    "value": "Sweden"
  }, {
    "name": "China",
    "value": "Armenia"
  }, {
    "name": "Indonesia",
    "value": "Uzbekistan"
  }, {
    "name": "Mexico",
    "value": "China"
  }, {
    "name": "France",
    "value": "China"
  }, {
    "name": "Russia",
    "value": "Brazil"
  }, {
    "name": "Palestinian Territory",
    "value": "Indonesia"
  }, {
    "name": "New Zealand",
    "value": "Kazakhstan"
  }, {
    "name": "Uganda",
    "value": "Indonesia"
  }, {
    "name": "Philippines",
    "value": "China"
  }, {
    "name": "Chile",
    "value": "China"
  }, {
    "name": "Argentina",
    "value": "Uruguay"
  }, {
    "name": "China",
    "value": "Brazil"
  }, {
    "name": "United States",
    "value": "China"
  }, {
    "name": "Belarus",
    "value": "Philippines"
  }, {
    "name": "Peru",
    "value": "Russia"
  }]
  
  
    export default (dataCountryDummy);